OnlineInternshipPortal/Models/Data/OnlineInternshipContext/Designation.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineInternshipPortal.Models.Data.OnlineInternshipContext
{
    public partial class Designation
    {
        public Designation()
        {
            Companies = new HashSet<Company>();
        }

        public int DesignationId { get; set; }
        public string DesignationName { get; set; }

        public virtual ICollection<Company> Companies { get; set; }
    }
}

OnlineInternshipPortal/Models/Data/ViewModel/DesignationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineInternshipPortal.Models.Data.ViewModel
{
    public class DesignationViewModel
    {
        [Key]
        [DisplayName("S/No.")]
        public int DesignationId { get; set; }
        [DisplayName("Designation name")]
        [RegularExpression(@"^[a-zA-Z-\s]*$", ErrorMessage = "Only Alphabets are allowed.")]
        public string DesignationName { get; set; }
    }
}

OnlineInternshipPortal/Controllers/DesignationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OnlineInternshipPortal.Models.Data.Services;
using OnlineInternshipPortal.Models.Data.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static OnlineInternshipPortal.Models.Enum;

namespace OnlineInternshipPortal.Controllers
{
    public class DesignationController : BaseController
    {
        private DesignationService _DesignationService;
        public DesignationController(DesignationService designationservice)
        {
            _DesignationService = designationservice;
        }
        
        // GET: DesignationController
        public ActionResult Index()
        {          
            return View();
        }

        [HttpGet]
        public ActionResult DesignationList()
        {
            var model = _DesignationService.GetDesignations();
            return Json(new { data = model });
        }

        // GET: DesignationController/Details/5
        public ActionResult Details(int id)
        {
            var model = _DesignationService.GetDesignationDetails(id);
            return View(model);
        }

        // GET: DesignationController/Create
        public ActionResult AddDesignation() 
        {
            return View();
        }

        // POST: DesignationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDesignation(DesignationViewModel model)
        {
            try
            {
                bool result = _DesignationService.AddDesignation(model);
                if(result == true)
                {
                    Alert("Congratulations", "New designation successfully added!", NotificationType.success);
                    return RedirectToAction(nameof(Index));
                }
               throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        // GET: DesignationController/Edit/5
        public ActionResult ChangeDesignation(int id) 
        {
            var model = _DesignationService.GetDesignationDetails(id);
            return View(model);
        }

        // POST: DesignationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangeDesignation(DesignationViewModel model) 
        {
            try
            {
                bool result = _DesignationService.UpdateDesignation(model);
                if (result)
                {
                    Alert("Congratulations", "Designation successfully updated!", NotificationType.success);
                    return RedirectToAction(nameof(Index));
                }
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        // POST: DesignationController/Delete/5
       [HttpDelete]
        public ActionResult RemoveDesignation(int id) 
        {
            try
            {
                bool result = _DesignationService.DeleteDesignation(id);
                if (result)
                {
                    return Json(new { success = true, message = "Designation successfully deleted!" });
                }
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineInternshipPortal/Views/Designation/AddDesignation.cshtml
@model OnlineInternshipPortal.Models.Data.ViewModel.DesignationViewModel

@{
    ViewData["Title"] = "Add Designation";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Add Designation</h1>
<br />
<div class="alert alert-info">
    Designation / Add designation
</div>
<br />
<div class="card au-card">

    <div class="card-body">
        <div class="row">
            <div class="col-lg-6">
                <form asp-action="AddDesignation">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="DesignationName" class="control-label"></label>
                        <input asp-for="DesignationName" class="form-control" />
                        <span asp-validation-for="DesignationName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary"><span class="fa fa-save"> </span> Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

OnlineInternshipPortal/Views/Designation/ChangeDesignation.cshtml
@model OnlineInternshipPortal.Models.Data.ViewModel.DesignationViewModel

@{
    ViewData["Title"] = "ChangeDesignation";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>Change designation</h1>

<hr />
<div class="alert alert-info">
   Designation/Edit designation
</div>

<br />
<div class="card au-card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <form asp-action="ChangeDesignation">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="DesignationId" />
                    <div class="form-group">
                        <label asp-for="DesignationName" class="control-label"></label>
                        <input asp-for="DesignationName" class="form-control" />
                        <span asp-validation-for="DesignationName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary"><span class="fa fa-save"> </span> Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

OnlineInternshipPortal/Views/Designation/Index.cshtml
@model  OnlineInternshipPortal.Models.Data.ViewModel.DesignationViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
}

<h1>List of designation</h1>

<br />
<div class="alert alert-info">
    Designation
</div>

<div class="card">
    <div class="card-header bg-transparent">
        <!-- Button trigger modal -->
        <a asp-controller="Designation" asp-action="AddDesignation" class="btn btn-primary text-capitalize">
            <span class="fas fa-plus"> Add new designation</span>
        </a>

    </div>

    <div class="card-body">
        <table id="designationtbl" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        S/No
                    </th>
                    <th>
                        Designation
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>

        </table>
    </div>

</div>

<!--Add db Modal-->
<div class="modal fade" id="addDesignationModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fa fa-user text-primary"> Add new designation</i></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-action="AddDesignation" method="post">
                <div class="modal-body">



                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label"><strong>Designation</strong></label>
                        <input asp-for="DesignationName" class="form-control" />
                        <span asp-validation-for="DesignationName" class="text-danger"></span>
                    </div>

                </div>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary"><span class="fa fa-save"> </span> Submit</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="fa fa-times"></span> Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Modal-->



@section Scripts{
    <script src="~/js/tablesjs/DesignationList.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    
}