OnlineInternshipPortal/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineInternshipPortal.Models.Data;
using OnlineInternshipPortal.Models.Data.Services;
using OnlineInternshipPortal.Models.Data.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static OnlineInternshipPortal.Models.Enum;

namespace OnlineInternshipPortal.Controllers
{
    public class CompanyController : BaseController
    {
        private CompanyService _CompanyService;
        private readonly UserManager<ApplicationUser> _userManager;
        public CompanyController(CompanyService companyService, UserManager<ApplicationUser> userManager)
        {
            _CompanyService = companyService;
            _userManager = userManager;
        }

        // GET: CompanyController
        public ActionResult Index()
        {

            return View();
        }
        [HttpGet]
        public ActionResult CompanyList()
        {
            var model = _CompanyService.GetCompanies();
            return Json(new { data = model });
        }


        [HttpGet]
        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> CompanyInformation()
        {
            var user = await _userManager.GetUserAsync(User);
            var model = _CompanyService.CompanyInformation(user);
            return View(model);
        }


        // GET: CompanyController/Details/5
     
        public ActionResult CompanyDetails(string id)
        {

            var model = _CompanyService.GetCompanyDetails(id);
            if (model.OtherIndustry == "None")
            {
                ViewData["OtherIndustry"] = "1";
            }
            return View(model);
        }

        // GET: CompanyController/Create
        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> AddCompany()
        {
            var user = await _userManager.GetUserAsync(User);
            var model = _CompanyService.CreateCompany(user);
            return View(model);
        }

        // POST: CompanyController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddCompany(CompanyViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            try
            {
                bool result = _CompanyService.AddCompany(model, user);
                if (result)
                {
                    Alert("Congratulations", "New company successfully added!", NotificationType.success);   
                }
                return RedirectToAction("Employers","Dashboard");
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        // GET: CompanyController/Edit/5
        [Authorize(Roles = "Employer")]
        public ActionResult ChangeCompanyDetails(string id)
        {
            var model = _CompanyService.GetCompanyDetails(id);
            if (model.OtherIndustry == "None")
            {
                ViewData["OtherIndustry"] = "1";
            }

            return View(model);
        }

        // POST: CompanyController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangeCompanyDetails(CompanyViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            try
            {
                bool result = _CompanyService.UpdateCompany(model, user);
                if (result)
                {
                    Alert("Congratulations", "Company information successfully updated!", NotificationType.success);
                  
                }
                return RedirectToAction(nameof(CompanyInformation));
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }


        // POST: CompanyController/Delete/5
        [HttpDelete]
        public ActionResult Removecompany(string id)
        {
            try
            {
                bool result = _CompanyService.DeleteCompany(id);
                if (result)
                {
                    return Json(new { success = true, message = "Data successfully deleted!" });
                }
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        //


    }
}

OnlineInternshipPortal/Controllers/InternsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineInternshipPortal.Models.Data;
using OnlineInternshipPortal.Models.Data.OnlineInternshipContext;
using OnlineInternshipPortal.Models.Data.Services;
using OnlineInternshipPortal.Models.Data.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static OnlineInternshipPortal.Models.Enum;

namespace OnlineInternshipPortal.Controllers
{
    public class InternsController : BaseController
    {

        private readonly InternService _internService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly OnlineInternshipContext _db;

        public InternsController(InternService internService, UserManager<ApplicationUser> userManager, OnlineInternshipContext db)
        {
            _internService = internService;
            _userManager = userManager;
            _db = db;
        }

        // GET: InternsController
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpGet]
         public ActionResult InternsList()
        {
            var model = _internService.GetInterns();
            return Json(new { data = model });
        }

        // GET: InternsController/Details/5
        public ActionResult InternDetails(string id)
        {
            var model = _internService.GetInternsDetails(id);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Student")]
        public async Task<ActionResult> StudentDetails()
        {
            var user = await _userManager.GetUserAsync(User); // Get students credentials
            int Countinterns = _db.Interns.Where(x => x.Email == user.Email && x.FirstName == user.FirstName).Count();
           
            if(Countinterns == 0)
            {
                Alert("Sorry", "Add your student information first before you can view student information", NotificationType.error);
                return RedirectToAction("Students", "Dashboard");
            }
            else
            {
                var model = _internService.GetStudentDetails(user);
                return View(model);
            }
           
        }

        [HttpGet]
        [Authorize(Roles = "Student")]
        public async Task<ActionResult> UpdateStudentDetails()  
        {
            var user = await _userManager.GetUserAsync(User); // Get students credentials
            int Countinterns = _db.Interns.Where(x => x.Email == user.Email && x.FirstName == user.FirstName).Count();

            if (Countinterns == 0)
            {
                Alert("Sorry", "Add your student information first before you can edit student information", NotificationType.error);
                return RedirectToAction("Students", "Dashboard");
            }
            else
            {
                var model = _internService.GetStudentDetails(user);
                return View(model);
            }
        }



        // GET: InternsController/Create
        [Authorize(Roles = "Student")]
        public async Task<ActionResult> AddInterns()
        {
            var user = await _userManager.GetUserAsync(User);
            var model = _internService.CreateInterns(user);
            return View(model);
        }

        // POST: InternsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddInterns(InternsViewModel model)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                if (CheckIfInternInformationAlreadyExist(user)) //if true then user has already filled intern information
                {
                    Alert("Sorry", "Intern information already exist", NotificationType.error);
                }
                else
                {
                    bool result = _internService.AddInterns(model);
                    if (result)
                    {
                        //sweet alert
                        Alert("Congratulations", "Intern information successfully added!", NotificationType.success);
                    }

                }

                return RedirectToAction("Students", "Dashboard");
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        // GET: InternsController/Edit/5
        public ActionResult UpdateInterns(string id) 
        {
            var model = _internService.GetInternsDetails(id);
            return View(model);
        }

        // POST: InternsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateInterns(InternsViewModel model)
        {
            try
            {
                
                bool result = _internService.UpdateInterns(model);
                if (result)
                {
                    Alert("Congratulations", "Intern information successfully updated!", NotificationType.success);                  
                }
                return RedirectToAction("Students", "Dashboard");
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        // GET: InternsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: InternsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //Check if Intern already added his/her intern information.Intern cannot fill two intern forms and upload two or mor CVs
        private bool CheckIfInternInformationAlreadyExist(ApplicationUser user)
        {
            int internCount = _db.Interns.Where(x => x.Email == user.Email && x.FirstName == user.FirstName).Count();
            if(internCount > 0)
            {
                return true;
            }

            return false;
        }

    }
}

OnlineInternshipPortal/Controllers/InternshipController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineInternshipPortal.Models.Data;
using OnlineInternshipPortal.Models.Data.OnlineInternshipContext;
using OnlineInternshipPortal.Models.Data.Services;
using OnlineInternshipPortal.Models.Data.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static OnlineInternshipPortal.Models.Enum;

namespace OnlineInternshipPortal.Controllers
{
    public class InternshipController : BaseController
    {
        private InternshipService _internshipService;
        private readonly UserManager<ApplicationUser> _userManager;
        private OnlineInternshipContext _Context;
        public InternshipController(InternshipService internshipService,UserManager<ApplicationUser> userManager,
            OnlineInternshipContext context
            )
        {
            _internshipService = internshipService;
            _userManager = userManager;
            _Context = context;
        }


        // GET: InternshipController
        [Authorize(Roles = "Employer")]
        public ActionResult Index()
        {
            
            return View();
        }
         public async Task<ActionResult> CompanyInternshipList() 
        {
            var user = await _userManager.GetUserAsync(User);
            var model = _internshipService.GetInternshipsByYourCompany(user);
            return Json(new { data = model });
        }

        // GET: InternshipController/Details/5
        public ActionResult Details(string id)
        {
            var model = _internshipService.GetInternshipDetails(id);
            return View(model);
        }

        // GET: InternshipController/Create
        [Authorize(Roles = "Employer")]
        public async Task<ActionResult> AddInternship()
        {
            var user = await _userManager.GetUserAsync(User);
            int verifyCompanyStatus = CheckIfCompanyHasBeenVerified(user);
            if(verifyCompanyStatus == 1)
            {
                Alert("Company denied", "Company has been denied.Contact adminstrator!", NotificationType.error);
                return RedirectToAction("Employers", "Dashboard");
            }
            else if(verifyCompanyStatus == 2)
            {
                Alert("Verify company", "Your company has not been approved yet", NotificationType.info);
                return RedirectToAction("Employers", "Dashboard");
            }
            else
            {
                var model = _internshipService.CreateInternship();
                return View(model);
            }

           
        }

        // POST: InternshipController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddInternship(InternshipViewModel model)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                

                bool result = _internshipService.AddInternships(model,user);
                if (result)
                {
                    Alert("Congratulations", "New internship successfully posted!", NotificationType.success);
                   
                }
                return RedirectToAction(nameof(Index));
                throw new Exception();
               
            }
            catch
            {
                throw;
            }
        }

        // GET: InternshipController/Edit/5
        [Authorize(Roles = "Employer")] 
        public ActionResult UpdateInternship(string id) 
        {
            var model = _internshipService.GetInternshipDetails(id);
            return View(model);
        }

        // POST: InternshipController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateInternship(InternshipViewModel model)
        {
            try
            {
                bool result = _internshipService.UpdateInternships(model);
                if (result)
                {
                    Alert("Congratulations", "Internship information successfully updated!", NotificationType.success);

                }
                return RedirectToAction(nameof(Index));
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        // GET: InternshipController/Delete/5
        public ActionResult RemoveInternship(string id)
        {
            var model = _internshipService.GetInternshipDetails(id);
            return View(model);
        }

        // POST: InternshipController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveInternship(string id, IFormCollection collection)
        {
            try
            {
                bool result = _internshipService.DeleteInternship(id);
                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                throw new Exception();
            }
            catch
            {
                return View();
            }
        }

        //[HttpPost]
        //public ActionResult InternshipSearch(int industryId)
        //{
        //    var data = _internshipService.SearchForInternships(industryId);
        //    return View(data);

        //}

        private int CheckIfCompanyHasBeenVerified(ApplicationUser user)
        {
            int a;
            Company company = _Context.Companies.Where(x => x.UserId == user.Id).FirstOrDefault();
            VerifyCompany verifyCompany = _Context.VerifyCompanies.Where(x => x.CompanyId == company.CompanyId).FirstOrDefault();
            int verifyId = verifyCompany.VerifyCategoryId;
            switch (verifyId)
            {
                case 1:
                    a = 1;
                    break;
                case 3:
                    a = 3;
                    break;
                default:
                    a = 2;
                    break;

            }

            return a;
        }

    }
}

OnlineInternshipPortal/Views/Dashboard/Employers.cshtml
@{
    ViewData["Title"] = "Students";
    Layout = "~/Views/Shared/_header.cshtml";
}

<style type="text/css">
    * {
        font-family: 'Montserrat', sans-serif;
        font-size: medium;
        color: #8E24AA
    }

    body {
        background-color: #F1F2F7
    }
</style>
<script type="text/javascript">
   /* $('.alert').alert()*/
    window.setTimeout(function () {
        $('#alertInformation').fadeTo(500, 0).slideUp(500, function () {
            $(this).alert('close');
        });

    },10000);
</script>

<div class="alert alert-info">
    <h3><span class="fa fa-dashboard"></span> Welcome to the Company dashboard </h3>
</div>
<div id="alertInformation" class="alert alert-warning alert-dismissible fade show" role="alert">
    <p>If this is your first login,then do the following instructions else close it</p>
    <ul type="square">
        <li>Go to Add Company to fill your company details</li>
        <li>If you made a mistake after submission of the information,Go to edit Company information to change it</li>
        <li>View your Company information by going to View Company information</li>
        
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<br />
<div class="form">

    <div class="card shadow-lg">
        <div class="card-header bg-transparent">
            <h5 class="text-black-50 text-uppercase">Quick Start</h5>
        </div>
        <div class="card-body">
            <div class="row" style="margin:auto;">

                <div class="col-md-3 py-2">
                    <a href="@Url.Action("AddCompany","Company")">
                        <div class="card" style="height:150px;">
                            <div class="card-body border border-danger shadow">
                                <div class="form-group">
                                    <div class="text-center ">
                                        <p><i class="fa  fa-user-plus fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label  style="cursor:pointer">Add new Company</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>


                <div class="col-md-3 py-2" style="margin:auto">
                    <a href="@Url.Action("CompanyInformation","Company")">
                        <div class="card" style="height:150px;">
                            <div class="card-body border border-warning shadow">
                                <div class="form-group">

                                    <div class="text-center">
                                        <p><i class="fa fa-edit fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label  style="cursor:pointer">View & Edit Company information</label>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </a>

                </div>

                <div class="col-md-3 py-2">
                    <a href="@Url.Action("Index","Internship")">
                        <div class="card" style="height:150px;">
                            <div class="card-body border border-success shadow">
                                <div class="form-group">

                                    <div class="text-center">
                                        <p><i class="fa  fa-newspaper-o fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label  style="cursor:pointer">Post Internship</label>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </a>
                </div>


            </div>
            <div class="row" style="margin:10px auto;">
                <div class="col-md-3 py-2">
                    <a href="@Url.Action("Index","InternApplication")">
                        <div class="card" style="height:150px;">
                            <div class="card-body border border-info shadow">
                                <div class="form-group">
                                    <div class="text-center">
                                        <p><i class="fa  fa-user-circle fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label style="cursor:pointer">Internship applicant</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 py-2" style="margin:auto">
                    <a href="@Url.Action("Index","HiredInterns")">
                        <div class="card" style="height:150px;">
                            <div class="card-body border border-secondary shadow">
                                <div class="form-group">
                                    <div class="text-center">
                                        <p class="text-primary"><i class="fas  fa-user-check fa-3x"></i></p>
                                    </div>
                                    <div class="text-center text-primary">
                                        <label style="cursor:pointer">Hired Interns</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 py-2">
                    <a href="@Url.Action("Index","SentEmails")">
                        <div class="card" style="height:150px;">
                            <div class="card-body border border-danger shadow">
                                <div class="form-group">
                                    <div class="text-center">
                                        <p><i class="fas fa-envelope-open-text fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label style="cursor:pointer">View Sent Mails</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>


            </div>
        </div>
    </div>

</div>
<br />

OnlineInternshipPortal/Views/Dashboard/Students.cshtml
@{
    ViewData["Title"] = "Students";
    Layout = "~/Views/Shared/_header.cshtml";
}

<style type="text/css">
    * {
        font-family: 'Montserrat', sans-serif;
        font-size: medium;
        color: #8E24AA
    }

    body {
        background-color: #F1F2F7
    }
</style>
<script type="text/javascript">
    /* $('.alert').alert()*/
    window.setTimeout(function () {
        $('#alertInformation').fadeTo(500, 0).slideUp(500, function () {
            $(this).alert('close');
        });

    }, 10000);
</script>

<div class="alert alert-info">
    <h3><span class="fa fa-dashboard"></span> Welcome to the student dashboard </h3>
</div>
<div id="alertInformation" class="alert alert-warning alert-dismissible fade show" role="alert">
   <p>If this is your first login,then do the following instructions else close it</p>
    <ul type="square">
        <li>Go to Add students to fill your details and upload CV</li>
        <li>If you made a mistake after submission of student information,Go to edit student information to change it</li>
        <li>View your student information by going to View student information</li>
        <li>Go to Message Inbox to view messages sent to you by companies</li>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true">&times;</span>
    </button>
</div>

<br />
<div class="form">

    <div class="card shadow-lg">
        <div class="card-header bg-transparent">
            <h5 class="text-black-50 text-uppercase">Quick Start</h5>
        </div>
        <div class="card-body">
            <div class="row" style="margin:auto;">

                <div class="col-md-3 py-2">
                    <a asp-controller="Interns" asp-action="AddInterns">
                        <div class="card shadow" style="height:150px;">
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="text-center ">
                                        <p><i class="fa  fa-user-plus fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label asp-controller="Interns" asp-action="AddInterns" style="cursor:pointer">Add student information</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>


                <div class="col-md-3 py-2" style="margin:auto">
                    <a asp-controller="Interns" asp-action="StudentDetails">
                        <div class="card shadow" style="height:150px;">
                            <div class="card-body">
                                <div class="form-group">

                                    <div class="text-center">
                                        <p><i class="fa  fa-user-circle fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label asp-controller="Interns" asp-action="StudentDetails" style="cursor:pointer">View student information</label>
                                    </div>

                                </div>
                            </div>

                        </div>
                    </a>

                </div>

                <div class="col-md-3 py-2">
                    <a asp-controller="Interns" asp-action="UpdateStudentDetails">
                        <div class="card shadow" style="height:150px;">
                            <div class="card-body">
                                <div class="form-group">

                                    <div class="text-center">
                                        <p><i class="fa  fa-edit fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label asp-controller="Interns" asp-action="UpdateStudentDetails" style="cursor:pointer">Edit student information</label>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </a>
                </div>


            </div>
            <div class="row" style="margin:10px auto;">
                <div class="col-md-3 py-2">
                    <a href="@Url.Action("Index","InternshipSearch")">
                        <div class="card shadow" style="height:150px;">
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="text-center">
                                        <p><i class="fa  fa-search fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label style="cursor:pointer">Search internships</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 py-2" style="margin:auto">
                    <a  href="@Url.Action("Index","ReceivedEmails")">
                        <div class="card shadow" style="height:150px;">
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="text-center">
                                        <p class="text-primary"><i class="fa  fa-envelope fa-3x"></i></p>
                                    </div>
                                    <div class="text-center text-primary">
                                        <label style="cursor:pointer">Message Inbox</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 py-2">
                    <a href="@Url.Action("StudentApplications","InternApplication")">
                        <div class="card shadow" style="height:150px;">
                            <div class="card-body">
                                <div class="form-group">
                                    <div class="text-center">
                                        <p><i class="fa fa-address-book-o fa-3x"></i></p>
                                    </div>
                                    <div class="text-center">
                                        <label style="cursor:pointer">View applications sent</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>


            </div>
        </div>
    </div>

</div>
<br />